# Generated by Django 5.2.6 on 2025-09-08 11:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleForm',
            fields=[
                ('Userid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Area', models.IntegerField()),
                ('OrientationOfRoof', models.IntegerField()),
                ('WeatherFile', models.CharField(blank=True, max_length=120, null=True)),
                ('WWR', models.FloatField()),
                ('SR_Base', models.FloatField()),
                ('IE_Base', models.FloatField()),
                ('SR_Propose', models.FloatField()),
                ('IE_Propose', models.FloatField()),
                ('Coolroof', models.BooleanField()),
                ('RoofContruction', models.CharField(blank=True, max_length=120, null=True)),
                ('ElectricityRate', models.FloatField()),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleForm_Base',
            fields=[
                ('Userid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Area', models.IntegerField()),
                ('OrientationOfRoof', models.IntegerField()),
                ('WeatherFile', models.CharField(blank=True, max_length=120, null=True)),
                ('WWR', models.FloatField()),
                ('ElectricityRate', models.FloatField()),
                ('Heating_Jan', models.FloatField()),
                ('Heating_Feb', models.FloatField()),
                ('Heating_March', models.FloatField()),
                ('Heating_April', models.FloatField()),
                ('Heating_May', models.FloatField()),
                ('Heating_June', models.FloatField()),
                ('Heating_July', models.FloatField()),
                ('Heating_August', models.FloatField()),
                ('Heating_Sept', models.FloatField()),
                ('Heating_Oct', models.FloatField()),
                ('Heating_Nov', models.FloatField()),
                ('Heating_Dec', models.FloatField()),
                ('Cooling_Jan', models.FloatField()),
                ('Cooling_Feb', models.FloatField()),
                ('Cooling_March', models.FloatField()),
                ('Cooling_April', models.FloatField()),
                ('Cooling_May', models.FloatField()),
                ('Cooling_June', models.FloatField()),
                ('Cooling_July', models.FloatField()),
                ('Cooling_August', models.FloatField()),
                ('Cooling_Sept', models.FloatField()),
                ('Cooling_Oct', models.FloatField()),
                ('Cooling_Nov', models.FloatField()),
                ('Cooling_Dec', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SimpleForm_Proposed',
            fields=[
                ('Userid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Area', models.IntegerField()),
                ('OrientationOfRoof', models.IntegerField()),
                ('WeatherFile', models.CharField(blank=True, max_length=120, null=True)),
                ('WWR', models.FloatField()),
                ('ElectricityRate', models.FloatField()),
                ('Heating_Jan', models.FloatField()),
                ('Heating_Feb', models.FloatField()),
                ('Heating_March', models.FloatField()),
                ('Heating_April', models.FloatField()),
                ('Heating_May', models.FloatField()),
                ('Heating_June', models.FloatField()),
                ('Heating_July', models.FloatField()),
                ('Heating_August', models.FloatField()),
                ('Heating_Sept', models.FloatField()),
                ('Heating_Oct', models.FloatField()),
                ('Heating_Nov', models.FloatField()),
                ('Heating_Dec', models.FloatField()),
                ('Cooling_Jan', models.FloatField()),
                ('Cooling_Feb', models.FloatField()),
                ('Cooling_March', models.FloatField()),
                ('Cooling_April', models.FloatField()),
                ('Cooling_May', models.FloatField()),
                ('Cooling_June', models.FloatField()),
                ('Cooling_July', models.FloatField()),
                ('Cooling_August', models.FloatField()),
                ('Cooling_Sept', models.FloatField()),
                ('Cooling_Oct', models.FloatField()),
                ('Cooling_Nov', models.FloatField()),
                ('Cooling_Dec', models.FloatField()),
            ],
        ),
    ]
